#!/usr/bin/env bash
# cron_pulse.sh — cron-based wake-pulse backend for environments without systemd.
#
# Reads config/session_schedule.json, converts window triggers to crontab lines,
# and installs them so cron calls scripts/executional/wake.sh at the right times.
# Idempotent: replaces any previously-installed block on each run.
#
# Usage:
#   bash tools/executional/cron_pulse.sh [install|remove|show]
#
#   install  (default) — generate and install crontab block
#   remove             — remove the managed block from the crontab
#   show               — print what would be installed, no changes
#
# The script marks its managed entries with a sentinel comment so it can find
# and replace them on subsequent runs without touching unrelated cron jobs.
#
# Cron must be available (crond or cron daemon running). On systems where cron
# is absent, schedule_one_off.py remains the only scheduling mechanism.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
SCHEDULE_FILE="${PROJECT_DIR}/config/session_schedule.json"
WAKE_SH="${PROJECT_DIR}/scripts/executional/wake.sh"
PERSONA_TXT="${PROJECT_DIR}/prompts/persona.txt"

SENTINEL_START="# BEGIN blank_node-wake-pulses"
SENTINEL_END="# END blank_node-wake-pulses"

ACTION="${1:-install}"

# ---------------------------------------------------------------------------
# Generate cron lines from session_schedule.json
# ---------------------------------------------------------------------------
_gen_cron_lines() {
    python3 - "$SCHEDULE_FILE" "$WAKE_SH" "$PERSONA_TXT" <<'PYEOF'
import json, sys, os

schedule_file, wake_sh, persona_txt = sys.argv[1], sys.argv[2], sys.argv[3]

# Use /bin/bash explicitly — cron may run with a minimal PATH.
wake_cmd = f"/bin/bash {wake_sh} {persona_txt}"

try:
    with open(schedule_file) as f:
        s = json.load(f)
except Exception as e:
    sys.stderr.write(f"ERROR: cannot read {schedule_file}: {e}\n")
    sys.exit(1)

seen = set()
lines = []
for w in s.get("windows", []):
    if not w.get("enabled", True):
        continue
    label = w.get("label", "")
    for t in w.get("triggers", []):
        if t in seen:
            continue
        seen.add(t)
        h, m = map(int, t.split(":"))
        # Cron field order: minute hour dom month dow command
        lines.append(f"{m:02d} {h:02d} * * *  {wake_cmd}  # {label}")

# Hourly probe at :15 — catches one_off[] entries (same role as in the systemd timer).
lines.append(f"15 * * * *  {wake_cmd}  # hourly-probe")

for line in lines:
    print(line)
PYEOF
}

# ---------------------------------------------------------------------------
# Build the full managed crontab block
# ---------------------------------------------------------------------------
_build_block() {
    echo "${SENTINEL_START}"
    echo "# Generated by cron_pulse.sh from ${SCHEDULE_FILE}"
    echo "# Do not edit manually — re-run cron_pulse.sh to regenerate."
    _gen_cron_lines
    echo "${SENTINEL_END}"
}

# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------
case "$ACTION" in
  show)
    _build_block
    ;;

  remove)
    current_crontab=$(crontab -l 2>/dev/null || true)
    if ! echo "$current_crontab" | grep -qF "$SENTINEL_START"; then
        echo "No managed block found in crontab — nothing to remove."
        exit 0
    fi
    new_crontab=$(echo "$current_crontab" | python3 -c "
import sys
lines = sys.stdin.read().splitlines()
out, inside = [], False
for l in lines:
    if '${SENTINEL_START}' in l:
        inside = True
        continue
    if '${SENTINEL_END}' in l:
        inside = False
        continue
    if not inside:
        out.append(l)
print('\n'.join(out))
")
    echo "$new_crontab" | crontab -
    echo "Removed managed crontab block."
    ;;

  install)
    new_block=$(_build_block)
    current_crontab=$(crontab -l 2>/dev/null || true)

    if echo "$current_crontab" | grep -qF "$SENTINEL_START"; then
        # Replace existing block
        updated=$(echo "$current_crontab" | python3 - "$new_block" <<'PYEOF'
import sys
content = sys.stdin.read()
new_block = sys.argv[1]
sentinel_start = "# BEGIN blank_node-wake-pulses"
sentinel_end = "# END blank_node-wake-pulses"
lines = content.splitlines()
out, inside = [], False
for l in lines:
    if sentinel_start in l:
        inside = True
        continue
    if sentinel_end in l:
        inside = False
        continue
    if not inside:
        out.append(l)
result = '\n'.join(out)
if result and not result.endswith('\n'):
    result += '\n'
result += new_block + '\n'
print(result, end='')
PYEOF
)
        echo "$updated" | crontab -
        echo "Updated managed crontab block."
    else
        # Append new block
        {
            if [ -n "$current_crontab" ]; then
                echo "$current_crontab"
                echo ""
            fi
            echo "$new_block"
        } | crontab -
        echo "Installed managed crontab block."
    fi

    echo ""
    echo "Active cron entries (managed block):"
    crontab -l | sed -n "/${SENTINEL_START}/,/${SENTINEL_END}/p"
    ;;

  *)
    echo "Usage: $0 [install|remove|show]" >&2
    exit 1
    ;;
esac
